services:
  backend:
    container_name: ${APP_NAME}_backend
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    stdin_open: true
    ports:
      - ${BACKEND_PORT}:3100
    volumes:
      - ./backend:/backend
      - ./.env:/backend/.env

  scraper:
    container_name: ${APP_NAME}_scraper
    build:
      context: scraper
      dockerfile: Dockerfile
    env_file:
      - .env
    stdin_open: true
    volumes:
      - ./scraper:/scraper
      - ./.env:/scraper/.env

  postgres:
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    image: postgres:16
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  minio:
    container_name: ${APP_NAME}_minio
    restart: unless-stopped
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z
    command: server /data --console-address ":9090"
    env_file:
      - .env
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9090"
    volumes:
      - minio:/data

volumes:
  postgres:
  minio:
